#!/bin/bash

EMQ_REPO="emqtt/emqttd"
RELEASES=$(curl -qsL https://api.github.com/repos/${EMQ_REPO}/tags | grep \"name\"|grep -v "rc"|grep -v "beta"|grep -v "alpha"|sed "s/^\s*\"name\"\s*:\s*\"\(v\([0-9]\+\.\)\+[0-9]\+\\)\"\s*,/\1/g")

latest=$(echo ${RELEASES}|cut -d" " -f1)
IMG=$(basename $DOCKER_REPO)
for tag in ${RELEASES}; do
    if [ "$tag" == "$latest" ]; then
        echo "============== Building ${IMG}:$tag as ${IMG}:latest"
        docker build --build-arg EMQ_VERSION=$tag -t ${DOCKER_REPO}:$tag -t ${DOCKER_REPO}:latest .
    else
        echo "============== Building ${IMG}:$tag"
        docker build --build-arg EMQ_VERSION=$tag -t ${DOCKER_REPO}:$tag .
    fi
done
