#!/bin/bash

EMQ_REPO="emqtt/emqttd"
RELEASES=$(curl -qsL https://api.github.com/repos/${EMQ_REPO}/tags | grep \"name\"|grep -v "rc"|grep -v "beta"|grep -v "alpha"|sed "s/^\s*\"name\"\s*:\s*\"\(v\([0-9]\+\.\)\+[0-9]\+\\)\"\s*,/\1/g")

IMG=$(basename $DOCKER_REPO)
for tag in ${RELEASES}; do
    echo "============== Building ${IMG}:$tag"
    docker build --build-arg EMQ_VERSION=$tag -t ${DOCKER_REPO}:$tag .
done

# Tag the top one as latest
latest=$(echo ${RELEASES}|cut -d" " -f1)
docker tag ${DOCKER_REPO}:$latest ${DOCKER_REPO}:latest